### ISSUE TITLE
Cannot unpack Data or Examples 

### ISSUE THREAD

**Issue by Madelinehazel** [fe4960/GRIPT_BCM#1]
Hello, 

I get errors when I try unpack Data.tar.gz and Examples.tar.gz, i.e.
`gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

I presume I need this files to run the program?

Thanks, 
Madeline

**Comment by javild** [comment]
same thing here @fe4960 
would be great to have a look at those

Thanks,
Javier

**Comment by fe4960** [comment]
Hi Madeline and Javier, 

Please download the Data.tar.gz and Examples.tar.gz from the the link below, following the instruction in README.md page in github.
https://zenodo.org/record/2583149#.XH1sucBKiJA
Due to the big size and complex .tar.gz file structure, the previous two files couldn't be unzipped. So I uploaded to zenodo, which are open accessed. Sorry for the inconvenience.

Best regards,
Jun
